from tilus.ir.inst import Instruction

from .cuda import (
    CopyAsyncCommitGroupInst,
    CopyAsyncInst,
    CopyAsyncWaitAllInst,
    CopyAsyncWaitGroupInst,
    LoadMatrixConfig,
    LoadMatrixInst,
    MmaDotConfig,
    MmaDotInst,
    SimtDotInst,
)
from .generic import (
    AllocateGlobalInst,
    AllocateRegisterInst,
    AllocateSharedInst,
    AssignInst,
    BroadcastElementwiseBinaryInst,
    CastInst,
    ElementwiseBinaryInst,
    ElementwiseUnaryInst,
    ExitInst,
    FormatPrintInst,
    FreeSharedInst,
    GlobalViewInst,
    LoadGlobalGenericInst,
    LoadGlobalInst,
    LoadSharedGenericInst,
    LoadSharedInst,
    PrintTensorInst,
    ShuffleDownInst,
    ShuffleUpInst,
    StoreGlobalGenericInst,
    StoreGlobalInst,
    StoreSharedGenericInst,
    StoreSharedInst,
    SyncReduceThreadsInst,
    SyncThreadsInst,
    ViewInst,
)
