name: Setup and Install Tilus
description: Sets up Python, checks out the repository, and installs Hidet and Tilus

inputs:
  python-version:
    description: Python version to set up
    required: false
    default: '3.10'

outputs:
  wheel-path:
    description: Path to the built Tilus wheel
    value: ${{ steps.install-tilus.outputs.wheel-path }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: hashFiles('/etc/buildkit/buildkitd.toml') != ''
      with:
        buildkitd-config: /etc/buildkit/buildkitd.toml
    - name: Install git and cmake
      run: |
        # Define a function to check and install packages safely
        install_package() {
          if command -v sudo &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y "$1"
          else
            apt-get update && apt-get install -y "$1"
          fi
        }

        # Install required packages
        install_package git
        install_package cmake
      shell: bash

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup proxy cache
      uses: nv-gha-runners/setup-proxy-cache@main
      if: hashFiles('/etc/buildkit/buildkitd.toml') != ''

    - name: Install Tilus
      id: install-tilus  # Preserve the ID for output
      uses: ./.github/actions/install-tilus
