name: "Build and Install Hidet Package"
description: "Clones the Hidet repository, builds it, and installs it."
inputs:
  hidet-access-token:
    description: "Hidet repository access token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install git and cmake
      run: |
        # Define a function to check and install packages safely
        install_package() {
          if command -v sudo &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y "$1"
          else
            apt-get update && apt-get install -y "$1"
          fi
        }

        # Install required packages
        install_package git
        install_package cmake
      shell: bash

    - name: Install Hidet repository
      run: |
        # Clone Hidet repository
        git clone https://${{ inputs.hidet-access-token }}@github.com/CentML/hidet.git
        cd hidet

        # Fetch all branches and checkout the required branch
        git fetch --all
        git checkout yaoyao/tilus

        # Build Hidet
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        cd ..

        # Install the package
        pip uninstall -y hidet
        pip install -e .
      shell: bash
