name: Format & Lint

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-and-lint:
    if: github.repository == 'NVIDIA/tilus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup and Install Tilus
        id: setup-and-install
        uses: ./.github/actions/setup-environment
        with:
          python-version: '3.10'

      - name: Check format and lint
        run: |
          pip list | grep -E 'ruff|mypy'  # show ruff and mypy versions
          bash .github/workflows/scripts/check-format-and-lint.sh
