name: Format & Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  format-and-lint:
    if: github.repository == 'hidet-org/tilus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup and Install Tilus
        id: setup-and-install
        uses: ./.github/actions/setup-environment
        with:
          python-version: '3.10'
          hidet-access-token: ${{ secrets.CENTML_HIDET_ACCESS }}

      - name: Check format and lint
        run: |
          pip list | grep -E 'ruff|mypy'  # show ruff and mypy versions
          bash .github/workflows/scripts/check-format-and-lint.sh
