name: Tests (Temporary)

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    if: github.repository == 'hidet-org/tilus'
    runs-on: "yaoyao-workstation"
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
      options: --gpus all
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Hidet
        uses: ./.github/actions/install-hidet
        with:
          hidet-access-token: ${{ secrets.CENTML_HIDET_ACCESS }}

      - name: Install Tilus
        id: install-tilus
        uses: ./.github/actions/install-tilus
        with:
          package-path: "."

      - name: Run tests
        run: pytest ./tests

      - name: Run examples
        run: bash .github/workflows/scripts/run-examples.sh
